# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Package publish

on:
  push:
    tags:
      - 'v*' # 触发条件：推送以 v 开头的tag

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/
      - name: Get version from git tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Update version in package.json
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"$version\"/" package.json
          sed -i "s/\"version\": \".*\"/\"version\": \"$version\"/" jsr.json
      - run: |
          pnpm install --frozen-lockfile
          pnpm build
      - run: pnpm publish @zhanghe/diamond --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Publish JSR package
        run: npx jsr publish
